---

#######################################
### ENABLE VARS
#######################################

### DATADOG

# foreman_enable_datadog: false

# foreman_enable_datadog_v6: false
# foreman_enable_datadog_v7: "{{ foreman_enable_datadog | bool }}"
