---
# noqa: var-naming[no-role-prefix]
# defaults file for foreman_content_datadog

#######################################
### URLS
#######################################

### DATADOG

foreman_repo_baseurl_datadog: https://yum.datadoghq.com


#######################################
### ENABLE VARS
#######################################

### DATADOG

foreman_enable_datadog: false

foreman_enable_datadog_v6: false
foreman_enable_datadog_v7: "{{ foreman_enable_datadog | bool }}"


#######################################
### PRODUCT DEFAULTS
#######################################

### DATADOG

foreman_products_defaults_download_policy_datadog: "{{ foreman_products_defaults_download_policy }}"
foreman_products_defaults_mirroring_policy_datadog: "{{ foreman_products_defaults_mirroring_policy }}"
foreman_products_defaults_verify_ssl_on_sync_datadog: "{{ foreman_products_defaults_verify_ssl_on_sync | bool }}"
foreman_products_defaults_http_proxy_policy_datadog: "{{ foreman_products_defaults_http_proxy_policy }}"
foreman_products_defaults_unprotected_datadog: "{{ foreman_products_defaults_unprotected | bool }}"


#######################################
### ORGANIZATION VARS
#######################################

### DATADOG

foreman_organization_datadog: "{{ foreman_organization }}"

foreman_organization_datadog_v6: "{{ foreman_organization_datadog }}"
foreman_organization_datadog_v7: "{{ foreman_organization_datadog }}"


#######################################
### CONTENT VIEW DEFAULTS
#######################################

### DATADOG

foreman_cv_allow_promote_datadog: "{{ foreman_cv_allow_promote | bool }}"

foreman_cv_allow_promote_datadog_v6: "{{ foreman_cv_allow_promote_datadog | bool }}"
foreman_cv_allow_promote_datadog_v7: "{{ foreman_cv_allow_promote_datadog | bool }}"


#######################################
### CONTENT
#######################################

foreman_content_credentials_datadog_main:
  - name: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-Datadog"
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', 'https://keys.datadoghq.com/DATADOG_RPM_KEY_CURRENT.public', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', role_path ~ '/files/DATADOG_RPM_KEY_CURRENT.public') }}"

foreman_content_credentials_datadog: "{{ ( foreman_content_credentials_datadog_main | default([]) if foreman_enable_datadog | bool else [] ) |
  union( foreman_content_credentials_datadog_v6 | default([]) if foreman_enable_datadog_v6 | bool else [] ) |
  union( foreman_content_credentials_datadog_v7 | default([]) if foreman_enable_datadog_v7 | bool else [] )
  }}"

foreman_products_datadog_main: []
foreman_products_datadog: "{{ ( foreman_products_datadog_main | default([]) if foreman_enable_datadog | bool else [] ) |
  union( foreman_products_datadog_v6 | default([]) if foreman_enable_datadog_v6 | bool else [] ) |
  union( foreman_products_datadog_v7 | default([]) if foreman_enable_datadog_v7 | bool else [] )
  }}"

foreman_content_views_datadog_main: []
foreman_content_views_datadog: "{{ ( foreman_content_views_datadog_main | default([]) if foreman_enable_datadog | bool else [] ) |
  union( foreman_content_views_datadog_v6 | default([]) if foreman_enable_datadog_v6 | bool else [] ) |
  union( foreman_content_views_datadog_v7 | default([]) if foreman_enable_datadog_v7 | bool else [] )
  }}"

foreman_operatingsystems_datadog_main: []
foreman_operatingsystems_datadog: "{{ ( foreman_operatingsystems_datadog_main | default([]) if foreman_enable_datadog | bool else [] ) |
  union( foreman_operatingsystems_datadog_v6 | default([]) if foreman_enable_datadog_v6 | bool else [] ) |
  union( foreman_operatingsystems_datadog_v7 | default([]) if foreman_enable_datadog_v7 | bool else [] )
  }}"

foreman_installation_media_datadog_main: []
foreman_installation_media_datadog: "{{ ( foreman_installation_media_datadog_main | default([]) if foreman_enable_datadog | bool else [] ) |
  union( foreman_installation_media_datadog_v6 | default([]) if foreman_enable_datadog_v6 | bool else [] ) |
  union( foreman_installation_media_datadog_v7 | default([]) if foreman_enable_datadog_v7 | bool else [] )
  }}"

foreman_activation_keys_datadog_main: []
foreman_activation_keys_datadog: "{{ ( foreman_activation_keys_datadog_main | default([]) if foreman_enable_datadog | bool else [] ) |
  union( foreman_activation_keys_datadog_v6 | default([]) if foreman_enable_datadog_v6 | bool else [] ) |
  union( foreman_activation_keys_datadog_v7 | default([]) if foreman_enable_datadog_v7 | bool else [] )
  }}"

foreman_sync_plan_products_datadog_main:
  - "{{ foreman_product_name_prefix | default('') }}Datadog"

foreman_sync_plan_products_datadog: "{{ ( foreman_sync_plan_products_datadog_main | default([]) if foreman_enable_datadog | bool else [] ) |
  union( foreman_sync_plan_products_datadog_v6 | default([]) if foreman_enable_datadog_v6 | bool else [] ) |
  union( foreman_sync_plan_products_datadog_v7 | default([]) if foreman_enable_datadog_v7 | bool else [] )
  }}"

